// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function DeleteTrack(arg1, arg2) {
  return window['go']['main']['App']['DeleteTrack'](arg1, arg2);
}

export function Download(arg1, arg2) {
  return window['go']['main']['App']['Download'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDownloadedSongs() {
  return window['go']['main']['App']['GetDownloadedSongs']();
}

export function GetPlaylists() {
  return window['go']['main']['App']['GetPlaylists']();
}

export function GetTracks(arg1) {
  return window['go']['main']['App']['GetTracks'](arg1);
}

export function InitBranding() {
  return window['go']['main']['App']['InitBranding']();
}

export function Login() {
  return window['go']['main']['App']['Login']();
}

export function SaveConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2, arg3);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}
