// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelDownload():Promise<string>;

export function DeleteTrack(arg1:string,arg2:string):Promise<string>;

export function Download(arg1:string,arg2:string):Promise<string>;

export function GetConfig():Promise<main.Config>;

export function GetDownloadedSongs():Promise<Array<string>>;

export function GetPlaylists():Promise<Array<Record<string, string>>>;

export function GetTracks(arg1:string):Promise<Array<string>>;

export function InitBranding():Promise<void>;

export function Login():Promise<string>;

export function SaveConfig(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SelectFolder():Promise<string>;
